name: Run Tests
on:
  push:
    branches: ['master', 'release']
  pull_request:
    branches: ['master', 'release']

jobs:
  test:
    runs-on: ubuntu-latest
    environment: TutorSeek
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run test-ci